on: [push]

name: build package

jobs:
  build:
    container:
      image: centos:7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout代码
        uses: actions/checkout@v2
      - name: build
        run: |
          ./packageOCSAgent.sh
